apiVersion: v1

kind: Service 

metadata:
  name: patient-service
 # namespace: patient-service
  labels:
    app: patient-service-svc-label

spec:
  ports:
  - port: 8080
    name: http

  selector:
    app: patient-service-v1-v3

  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: patient-service-deployment-v1
 # namespace: patient-service
  labels:
    app: patient-service-dep-label

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: patient-service-v1-v3

  template: # template for the pods
    metadata:
      labels:
        app: patient-service-v1-v3
        version: v1
        #application: petclinic

    spec:
      containers:
      - name: customers-service-ver1
        image: saurabh2204/online-appointment-patient-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9899
